# Generated by Django 6.0 on 2026-01-07 12:57

import datetime
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_variety', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('sub_district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=255)),
                ('ekyf_id', models.CharField(max_length=15, unique=True)),
                ('f_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 or 11 digit Phone number.', regex='^[0-9]{10,11}$')])),
                ('f_photo', models.ImageField(blank=True, null=True, upload_to='farmer/')),
                ('aadhar_no', models.CharField(error_messages={'unique': 'Adhaar No Alredy Exist in the site'}, max_length=12, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('harvested_date', models.DateField(default=datetime.date.today)),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('TON', 'Metric Tons'), ('Q', 'Quintal (100kg)')], max_length=3)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField(null=True)),
                ('stored_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_available', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('O', 'Open'), ('R', 'Reserved'), ('S', 'SOLD')], default='O', max_length=1)),
                ('stock_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.stockdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcrops', to='farmer.cropmaster')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.stockmaster'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='stock',
            field=models.ManyToManyField(through='farmer.StockMaster', to='farmer.cropmaster'),
        ),
    ]
