# Generated by Django 6.0 on 2026-01-16 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_no',
            field=models.CharField(error_messages={'unique': 'Adhaar No Alredy Exist in the site'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Adhaar card Number. Please Enter Valid Adhaar card Number', regex='^[2-9]{1}[0-9]{11}$')]),
        ),
    ]
