# Generated by Django 6.0 on 2026-01-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='farmer.stockmaster'),
        ),
    ]
