# Generated by Django 6.0 on 2026-02-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_alter_stockdetail_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='ekyf_id',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid 14 digit ekyf ID', regex='/^[a-zA-Z]{2}[0-9]{12}$/')]),
        ),
    ]
