# Generated by Django 6.0 on 2026-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_farmer_ekyf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='aadhar_photo',
            field=models.ImageField(default='', upload_to='farmer/aadhar/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_id_photo',
            field=models.ImageField(default='', upload_to='farmer/farmer_id/'),
        ),
    ]
