# Generated by Django 6.0 on 2026-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_farmer_aadhar_photo_farmer_farmer_id_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('commodity', models.CharField(max_length=20)),
                ('target_date', models.DateField()),
                ('market_name', models.CharField(max_length=30)),
                ('variety', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=20)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_lag_7d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_lag_14d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_lag_30d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_7d_avg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_30d_avg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temp_mean_lag_30d', models.FloatField(max_length=5)),
                ('rainfall_mm_30d_avg', models.FloatField(max_length=5)),
                ('rainfall_mm_30d_sum', models.FloatField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
