# Generated by Django 6.0 on 2026-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_commoditymaster_districtmaster_grademaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmaster',
            name='market_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='priceprediction',
            name='market_name',
            field=models.CharField(max_length=50),
        ),
    ]
