# Generated by Django 6.0 on 2026-01-07 12:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.date.today)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.bidding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcrops', to='farmer.cropmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('intake_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('TON', 'Metric Tons'), ('Q', 'Quintal (100kg)')], max_length=3)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField(null=True)),
                ('warehouse_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.stockmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=255)),
                ('gst_no', models.CharField(help_text='Format: 22AAAAA0000A1Z5', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-digit GST number.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('w_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 or 11 digit Phone number.', regex='^[0-9]{10,11}$')])),
                ('w_photo', models.ImageField(blank=True, null=True, upload_to='wholesaler/')),
                ('aadhar_no', models.CharField(error_messages={'unique': 'Adhaar No Alredy Exist in the site'}, max_length=12, unique=True)),
                ('business_proof', models.FileField(upload_to='wholesaler/business_proof/')),
                ('business_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('V', 'Verified'), ('U', 'Unverified')], default='U', max_length=1)),
                ('pan_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit PAN number (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('biddings', models.ManyToManyField(through='wholesaler.Bidding', to='farmer.listing')),
                ('stock', models.ManyToManyField(through='wholesaler.StockMaster', to='farmer.cropmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='w_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.wholesaler'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='bidder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.wholesaler'),
        ),
    ]
