# Generated by Django 6.0 on 2026-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0002_alter_wholesaler_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Payment'), ('Review', 'Payment Under Review'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
    ]
