# Generated by Django 6.0 on 2026-02-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0003_remove_orders_qty_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaler.stockmaster'),
        ),
    ]
