# Generated by Django 6.0 on 2026-02-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_farmer_ekyf_id'),
        ('wholesaler', '0004_alter_stockdetail_stock_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together={('l_id', 'bidder_id')},
        ),
    ]
