# Generated by Django 6.0 on 2026-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0005_alter_bidding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='aadhar_photo',
            field=models.ImageField(default='', upload_to='wholesaler/aadhar/'),
        ),
    ]
